# Generated by Django 2.0 on 2018-08-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256)),
                ('real_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('wk_id', models.CharField(max_length=32, unique=True, verbose_name='工号')),
                ('email', models.EmailField(max_length=64)),
                ('phone_num', models.CharField(max_length=24, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '审核员',
                'verbose_name_plural': '审核员',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='产品名称')),
                ('synopsis', models.TextField(verbose_name='简介')),
                ('origin', models.CharField(max_length=64, verbose_name='产地')),
                ('classify', models.CharField(max_length=16, verbose_name='分类')),
                ('is_audit', models.BooleanField(default=False, verbose_name='审核情况')),
                ('create_date', models.DateTimeField(verbose_name='生产日期')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('Audit_date', models.DateTimeField(verbose_name='审核日期')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.AuditorUser', verbose_name='审核员')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256)),
                ('real_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('company', models.CharField(max_length=64, unique=True, verbose_name='公司名')),
                ('email', models.EmailField(max_length=64)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='producers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.ShopUser', verbose_name='商家'),
        ),
    ]
